const config = require('../config');

const CARTESIA_ENDPOINT = 'https://api.cartesia.ai/tts/bytes';
const CARTESIA_VERSION = '2026-03-01';

/**
 * Converts text to speech using Cartesia Sonic 3.
 * Returns a Buffer of MP3 audio data.
 *
 * Text may contain inline SSML tags (break, speed, volume, emotion)
 * generated by Claude. These pass through directly to Cartesia.
 *
 * Supports AbortSignal for barge-in cancellation and retries once on failure.
 */
async function synthesize(text, options = {}) {
    const startTime = Date.now();
    const signal = options.signal || null;

    const requestBody = {
        model_id: 'sonic-3',
        transcript: text,
        voice: {
            mode: 'id',
            id: config.cartesia.voiceId
        },
        output_format: {
            container: 'mp3',
            bit_rate: 128000,
            sample_rate: 48000
        },
        language: 'en'
    };

    const fetchOptions = {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${config.cartesia.apiKey}`,
            'Cartesia-Version': CARTESIA_VERSION,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(requestBody),
        signal
    };

    let response;

    try {
        response = await fetch(CARTESIA_ENDPOINT, fetchOptions);
    } catch (err) {
        if (err.name === 'AbortError') {
            console.info('[cartesia] Request cancelled (barge-in or timeout)');
            throw err;
        }

        // Retry once after 500ms
        console.warn('[cartesia] First attempt failed, retrying in 500ms', { error: err.message });
        await new Promise((r) => setTimeout(r, 500));

        try {
            response = await fetch(CARTESIA_ENDPOINT, fetchOptions);
        } catch (retryErr) {
            if (retryErr.name === 'AbortError') throw retryErr;
            throw retryErr;
        }
    }

    if (!response.ok) {
        const errorBody = await response.text().catch(() => 'unknown');
        console.error('[cartesia] API error', {
            status: response.status,
            body: errorBody.substring(0, 200)
        });
        throw new Error(`Cartesia TTS error: ${response.status}`);
    }

    // Response is raw audio bytes
    const arrayBuffer = await response.arrayBuffer();
    const audioBuffer = Buffer.from(arrayBuffer);

    const latencyMs = Date.now() - startTime;
    console.info('[cartesia] TTS complete', {
        textLen: text.length,
        audioBytes: audioBuffer.length,
        latencyMs
    });

    return audioBuffer;
}

module.exports = { synthesize };
